#----------------------------------------------
# cubosemantico.py
# cubosemantico
# Manuel Calzado Maycotte A00811102
# Juan Paulo Lara Rodriguez A00999823
# CREADO: 18/03/2014
#----------------------------------------------

cubo_semantico = {
  	"entero": {
			"entero": {
				"+":"entero", 
				"-":"entero", 
				"*":"entero", 
				"/":"entero", 
				">":"booleano", 
				">=":"booleano",
				"<=":"booleano",
				"<":"booleano", 
				"=":"entero",
				"==": "booleano", 
				"!=":"booleano",
				"&&":"error", 
				"||":"error",
				}, 
			"flotante": {
				"+":"flotante", 
				"-":"flotante", 
				"*":"flotante", 
				"/":"flotante", 
				">":"booleano", 
				">=":"booleano",
				"<=":"booleano",
				"<":"booleano", 
				"=":"entero", 
				"==": "booleano",
				"!=":"booleano",
				"&&":"error", 
				"||":"error",
				}, 
			"texto": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"booleano": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			"lista": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			}, 
		"flotante":{
			"entero": {
				"+":"flotante", 
				"-":"flotante", 
				"*":"flotante", 
				"/":"flotante", 
				">":"booleano", 
				">=":"booleano",
				"<=":"booleano",
				"<":"booleano", 
				"=":"flotante", 
				"==": "booleano",
				"!=":"booleano",
				"&&":"error", 
				"||":"error",
				}, 
			"flotante": {
				"+":"flotante", 
				"-":"flotante", 
				"*":"flotante", 
				"/":"flotante", 
				">":"booleano", 
				">=":"booleano",
				"<=":"booleano",
				"<":"booleano", 
				"=":"flotante",
				"==": "booleano", 
				"!=":"booleano",
				"&&":"error", 
				"||":"error",
				}, 
			"texto": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"booleano": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			"lista": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			}, 
		"texto":{
			"entero": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"flotante": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"texto": {
				"+":"texto", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"texto", 
				"==": "booleano",
				"!=":"booleano",
				"&&":"error", 
				"||":"error",
				}, 
			"booleano": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			"lista": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			}, 
		"booleano":{
			"entero": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"flotante": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==":"error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"texto": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==":"error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"booleano": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"booleano", 
				"==":"booleano",
				"!=":"booleano",
				"&&":"booleano", 
				"||":"booleano",
				},
			"lista": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			},
		"lista":{
			"entero": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"flotante": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==":"error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"texto": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==":"error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				}, 
			"booleano": {
				"+":"error", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==":"error",
				"!=":"error",
				"&&":"error", 
				"||":"error",
				},
			"lista": {
				"+":"lista", 
				"-":"error", 
				"*":"error", 
				"/":"error", 
				">":"error", 
				">=":"error",
				"<=":"error",
				"<":"error", 
				"=":"error", 
				"==": "booleano",
				"!=":"booleano",
				"&&":"error", 
				"||":"error",
				},

			},

		}
