<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spy</string>
	</array>
	<key>name</key>
	<string>Snappy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#controlKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#characterOperator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dataTypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blockDefinitions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionDefinitions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#actionKeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotedString</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>controlKeywords</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(si|SI|entonces|ENTONCES|sino|SINO|finsi|FINSI|mientras|MIENTRAS|hacer|HACER|finmientras|FINMIENTRAS|regresa|REGRESA)\b)</string>
			<key>name</key>
			<string>keyword.control.snappy</string>
		</dict>
		<key>characterOperator</key>
		<dict>
			<key>match</key>
			<string>(\.|\|\||\+=|\+|\*=|\*|\\=|\\|/=|/|=|-=|-|&lt;|&lt;=|&gt;|&gt;=|&amp;=|&amp;|\^|\^=|&gt;&gt;=|&gt;&gt;|&lt;&lt;=|&lt;&lt;|:=)</string>
			<key>name</key>
			<string>keyword.operator.snappy</string>
		</dict>
		<key>dataTypes</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(entero|ENTERO|flotante|FLOTANTE|texto|TEXTO|booleano|BOOLEANO)\b)</string>
			<key>name</key>
			<string>entity.name.function.snappy</string>
		</dict>
		<key>blockDefinitions</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(INICIOBLOQUE|iniciobloque|FINBLOQUE|finbloque)\b)</string>
			<key>name</key>
			<string>support.function.snappy</string>
		</dict>
		<key>functionDefinitions</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(INICIOFUNCION|FINFUNCION|INICIOPRINCIPAL|INICIOPROGRAMA|FINPROGRAMA|FINPRINCIPAL|iniciofuncion|finfuncion|PARAMETROS|parametros|inicioprincipal|finprograma|inicioprograma|finprincipal)\b)</string>
			<key>name</key>
			<string>support.type.snappy</string>
		</dict>
		<key>actionKeywords</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(MOVER|RETROCEDE|retrocede|GIRARIZQUIERDA|GIRARDERECHA|DESPINTAR|PINTAR|PEDIRALUSUARIO|DECIRALUSUARIO|mover|girarizquierda|girarderecha|despintar|pintar|pediralusuario|deciralusuario|crear|CREAR)\b)</string>
			<key>name</key>
			<string>constant.language.snappy</string>
		</dict>
		<key>quotedString</key>
		<dict>
			<key>match</key>
			<string>(")([^"]|"")*(")</string>
			<key>name</key>
			<string>string.quoted.double.snappy</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.snappy</string>
	<key>uuid</key>
	<string>975d5447-0eb5-444c-a471-5934193ca1ea</string>
</dict>
</plist>